### ISSUE TITLE
Add psql CLI

### ISSUE THREAD

**Issue by wayneeseguin** [cloudfoundry-community/toolbelt-boshrelease#24]
Add psql CLI for PostgreSQL database interaction.

**Comment by jhunt** [comment]
We have a MySQL client... https://github.com/cloudfoundry-community/toolbelt-boshrelease/tree/master/jobs/toolbelt-mysql-client

:trollface:

**Comment by wayneeseguin** [comment]
That's a great way to access `/dev/null` and `/dev/random`, thanks.
